# Generated by Django 2.2.6 on 2020-08-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
