# Generated by Django 2.2.6 on 2020-08-31 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
